### ISSUE TITLE
Add "Debug" tab to the settings page

### ISSUE THREAD

**Issue by ExpandedFronts** [ExpandedFronts/Revisr#13]
Allow users to quickly troubleshoot most common issues with installation.

Should be able to cover:

* Is the exec() function enabled?
* Is Git recognized as installed by Revisr?
* Is the path to Git set correctly on the system? (If not, allow override)
* Is the path to MySQL set correctly on the system? (If not, allow override)
* Are the necessary permissions set?

**Comment by mgshaw** [comment]
Closed with #33
