### ISSUE TITLE
Add option for change-based DB tracking

### ISSUE THREAD

**Issue by ExpandedFronts** [ExpandedFronts/revisr#15]
Add an option to backup and commit changes as they occur, preferably incrementally.

If enabled, any changes to the database for the tracked tables should be automatically committed as changes are made. A possible implementation would be to create a child class of the wpdb object to act as middleware between WordPress and Revisr.

TODO:
* Test on resource-intensive sites with large database.
* Determine best approach for incremental (as opposed to full) database backups.

**Comment by JavierSegoviaCordoba** [comment]
Any update about this?

**Comment by kalyanGK1** [comment]
How to change db from revisr if we have multiple db's
