### ISSUE TITLE
Automatically assign Git Username & Email based on current user

### ISSUE THREAD

**Issue by ExpandedFronts** [ExpandedFronts/Revisr#16]
Add an option (or enable by default) for users to automatically use their WordPress username and email address for making new commits.

TODO:
* Determine approach for default username & email address (for automatic commits)
* Remove options from settings page? (decisions, not options)

**Comment by JDGrimes** [comment]
+1 This would be great when multiple people are working on the same site.

**Comment by mgshaw** [comment]
This has been completed with #33.
