### ISSUE TITLE
Error handling for pulls

### ISSUE THREAD

**Issue by ExpandedFronts** [ExpandedFronts/Revisr#17]
If the user has successfully added the Revisr webhook to another service like BitBucket or GitHub, but is also having an authentication issue with the remote repository, Revisr will both throw an error due to the authentication issue and log that it pulled the unpulled commits. 

Example:

* Error pulling changes from the remote repository.
* Pulled #98764 from the remote repository.
* Pulled #123456 from the remote repository.

**Comment by mgshaw** [comment]
Closing this in favor of issue #39
