### ISSUE TITLE
Update commit meta boxes

### ISSUE THREAD

**Issue by ExpandedFronts** [ExpandedFronts/Revisr#18]
The "Publish" meta box should likely be replaced with a custom meta box:
![screen shot 2014-12-29 at 4 20 17 am](https://cloud.githubusercontent.com/assets/6504708/5582297/677c073c-9035-11e4-9997-5dfd09b95b45.png)

The "Save Draft" functionality is useless with Revisr and hitting "Enter" automatically saves a draft instead of creating the commit.

The text in this box should also be updated to be less confusing.

**Comment by mgshaw** [comment]
Closed with #33
