### ISSUE TITLE
Allow special characters in password

### ISSUE THREAD

**Issue by mattgrshaw** [ExpandedFronts/revisr#23]
Since Git does it's own escaping for the fields stored in the ".git/config", we need to make sure that any special characters that could be part of the user's password are being escaped correctly, see:

https://wordpress.org/support/topic/permissions-error-10?replies=10

In this case, the "@" symbol was causing an authentication issue (either because it was triggering the end of the password or wasn't being escaped correctly).

**Comment by mgshaw** [comment]
This is outside of our control since this won't even work inside Git.

**Comment by mgshaw** [comment]
We could likely cache the password in Git as shown here:
https://help.github.com/articles/caching-your-github-password-in-git/
