### ISSUE TITLE
Save working copy changes when pushing

### ISSUE THREAD

**Issue by JDGrimes** [ExpandedFronts/Revisr#28]
Right now, when the commits are pushed, `reset()` is called first, destroying any uncommitted local changes. There is probably a good reason for this, but it would be nice to keep the local changes instead, if possible. Perhaps they could be stashed and then popped back out after the push, if that is necessary.

It would at least be nice if there was a message telling the user that they have uncommitted local changes that will be destroyed. I don't think that there is such a warning currently (though I could be wrong).

**Comment by mgshaw** [comment]
@JDGrimes Thanks for mentioning this, I thought this had been addressed with issue #6 in the previous previous release but I see now that there's another call to reset() that needs to be taken out in Revisr_Process.

**Comment by JDGrimes** [comment]
Great! Thanks for the quick response.

**Comment by mgshaw** [comment]
This has been fixed with #33
