### ISSUE TITLE
breaks dashboard after activating plugin

### ISSUE THREAD

**Issue by adrelanos** [ExpandedFronts/Revisr#29]
Just now installed using wordpress's usual plugin installer. After activating the plugin, the dashboard is broken. Doesn't load at all anymore.

Using wordpress 4.1.

Need any debug info?

**Comment by mgshaw** [comment]
Hi,

That's strange, that's the first report I've seen of this. Did you get any errors, and does the server meet Revisr's installation requirements (exec enabled and Git installed)? What kind of server was it? Local on MAMP or WAMP or a remote linux server?

**Comment by adrelanos** [comment]
> Did you get any errors

No. The page just never loads.

> exec enabled

```
/etc/php5# grep -r disable_functions *
apache2/php.ini:disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
apache2/php.ini.ucf-dist:disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,
cli/php.ini:disable_functions =
cli/php.ini.ucf-dist:disable_functions =
```

> Git installed

```
git --version
git version 1.7.10.4
```

> What kind of server was it? Local on MAMP or WAMP or a remote linux server?

Remote apache2 (on Debian wheezy).

**Comment by mgshaw** [comment]
Hi,

If you get a chance, can you confirm if the issue persists with what's on dev?
https://github.com/ExpandedFronts/Revisr/archive/dev.zip

**Comment by adrelanos** [comment]
Same issue.

**Comment by mgshaw** [comment]
Thanks for testing that out. The only thing that comes to mind is that the path to Git isn't available in Apache. I added a check for this in the settings but unfortunately it sounds like you're not getting that far. 

You may have some luck defining the path to git in your wp-config like so:

`define( 'REVISR_GIT_PATH', '/usr/bin/git' );`

Where `/usr/bin/git` is the path to your Git installation, which you may be able to find by running `which git` in command line.

**Comment by adrelanos** [comment]
That worked. Added this to the child theme functions.php. We are using the default /usr/bin/git path. (Just did "apt-get install git" on Debian. Nothing fancy.)

This is by the way how I installed the plugin.

```
cd /var/www/blog/wp-content/plugins
wget https://github.com/ExpandedFronts/Revisr/archive/dev.zip
unzip dev.zip
mv Revisr-dev Revisr
```

I am not a php, wordpress coder. But could you make it default to /usr/bin/git and fail gracefully if it could not be detected?

**Comment by mgshaw** [comment]
Glad that worked. The reason it's set up the way it is right now is that just using "git" will work on most environments (even on Windows) if the environment path to Git is set (i.e. if Git was installed and you selected the option to make it available to other scripts).

I do think it's time to revisit that thinking and at the very least make sure that the lack of a connection to Git doesn't break anything in WordPress, so will be looking into this further.

**Comment by mgshaw** [comment]
This should be fixed with the latest release, if git isn't detected, this will be mentioned in the setup wizard and give you an option on-screen to define the path to Git.
