### ISSUE TITLE
doesn't notice .git folder permission issues

### ISSUE THREAD

**Issue by adrelanos** [ExpandedFronts/Revisr#35]
Long story short, by convention on our server the webapps folders are owned by user `www-data` and `.git` folders are owned by regular users.

I was wondering, why revisr reports the same uncommitted files after committing them. Therefore, I suspect it does not check if git reported success, i.e. exited with code 0. Please consider adding some rudimentary failure notification handling, i.e. checking git exit codes and notifying the user if something failed.

Another option would be to check if permissions to write into the `.git` folder are sufficient.

**Comment by mgshaw** [comment]
Hi,

Revisr does check if both `.git` and `.git/config` is writeable on the Revisr Help tab in the settings page under `File Permissions`. Was this not working correctly for you?

I do think that the error handling needs to be tweaked (Revisr does check the git exit codes, but the error handling for new commits does need to be improved further and made more obvious to end-users).

**Comment by adrelanos** [comment]
I didn't look at the Revisir Help. Just noticed, that menu bar in the very top kept telling me, that commits are not made, that I thought I just did. The page that is shown after commit does not show that it actually failed.

**Comment by mgshaw** [comment]
Closing this issue in favor of issue #39 to keep everything in one spot
