### ISSUE TITLE
Use environment variables to switch between staging/production/development automatically

### ISSUE THREAD

**Issue by cromulus** [ExpandedFronts/Revisr#38]
I don't know if this is possible, but it would be great to be able to have revisr detect what config to load based on an [environment variable](http://en.wikipedia.org/wiki/Environment_variable).

I'd love to be able to use chef to provision machines automatically using Revisr and an environment variable.

Is this currently possible and just not in the docs?

Thanks!

**Comment by mgshaw** [comment]
Hello,

Can you please let me know which config that you're referring to (the WordPress config file, or settings specific to Revisr?)

Currently, Revisr stores some environment-specific settings such as the MySQL path, the auto-push/auto-pull settings, the Development URL, etc. in the local ".git/config" file for the repo. This lets Revisr store settings that aren't tracked in the repo so they can be separate on each environment.

**Comment by cromulus** [comment]
ahh, ok. that makes sense. Thanks!
