### ISSUE TITLE
Git username and email aren't displaying on initial save

### ISSUE THREAD

**Issue by jimwebb** [ExpandedFronts/Revisr#43]
To replicate, using Revisr 1.9.1 on WP 4.1.1:

1. Go to Revisr > Settings
2. Enter a new git username or email address
3. Click Save
4. The displayed values don't match what you just entered
5. But if you reload or click back on "settings" they are indeed saved properly.

**Comment by jimwebb** [comment]
I think they're both saved properly. The email address is, anyway. The name isn't (for me).

**Comment by mgshaw** [comment]
Just confirmed this... Looking into it now and will likely release fix this afternoon.

**Comment by mgshaw** [comment]
This has been fixed in Revisr 1.9.2. Thanks for reporting the issue!
