### ISSUE TITLE
Anonymous function in class-revisr-commits throws error

### ISSUE THREAD

**Issue by jimwebb** [ExpandedFronts/Revisr#46]
Using PHP 5.2 with Revisr 1.9.3 on WP 4.1.1, the following fatal error is returned:

Parse error: syntax error, unexpected T_FUNCTION in /home/graffiatodc/webapps/mic_wp/wp-content/plugins/revisr/includes/class-revisr-commits.php on line 113

There's an anonymous function there, which is functionality that's only available in PHP 5.3 or newer. Bummer.

Using create_function() is a possibility, but it's a little bit icky, right? Could this particular instance be converted to a named function? Sorry.

**Comment by mgshaw** [comment]
Thanks, didn't catch this since PHP Unit requires 5.3+.

**Comment by mgshaw** [comment]
Hi Jim, this should be fixed with 1.9.4. Thanks again!

**Comment by jimwebb** [comment]
Thanks, Matt! That's awesome!
