### ISSUE TITLE
Where is merge?

### ISSUE THREAD

**Issue by mvaneijgen** [ExpandedFronts/Revisr#49]
I can see in the [changeling](https://revisr.io/change-log/) that in version 1.7 the ability to merge in implemented, but I can't find it nor can I find anything on this ins the docs. 

How do you merge commits in the wp-admin?

**Comment by mgshaw** [comment]
Hi,

You can do this from the "Branches" screen - you will see an option to merge another branch into your current branch. It will use the "theirs" merge strategy (in the event of conflicts, keep the version from the branch being merged in), and you will also have the option to import the latest DB backup files that are on that branch.

Let me know if you have any questions, thanks!
