### ISSUE TITLE
Configuration option Path to git

### ISSUE THREAD

**Issue by vincentml** [ExpandedFronts/Revisr#50]
Would it be possible to add a configuration option to Revisr to specify the path to git? I imagine this would be similar to the current configuration option "Path to MySQL". I'm using a shared hosting server that has git installed in such a way that, by default, git must be invoked using a full path.

**Comment by vincentml** [comment]
After searching the Revisr source I found this option already exists, and it works. To configure the path to git I just had to edit wp-config.php and add a line:

define('REVISR_GIT_PATH', '/usr/local/cpanel/3rdparty/bin/git');

Maybe this could be mentioned in the installation instructions.

**Comment by mgshaw** [comment]
Hi,

It was in the docs, http://docs.revisr.io/article/27-error-committing-files, but I can see how easily that could be missed (I had to dig for it myself). Leaving this open as a reminder to update docs to make things easier to search.

**Comment by mgshaw** [comment]
Closing this as it's now super easy to define the path to git from the settings page.

**Comment by younes0** [comment]
**Useful for roots/bedrock users**
Add in '/application/application.php':
```php
define('REVISR_GIT_DIR', __DIR__.'/..');
```
