### ISSUE TITLE
Add action hooks to make Revisr more extensible

### ISSUE THREAD

**Issue by mgshaw** [ExpandedFronts/Revisr#53]
Users may want to hook into action hooks placed before or after major Revisr actions so they can run custom scripts. Some hooks that are worth looking into including are listed below.

* revisr_pre_commit
* revisr_post_commit
* revisr_pre_pull
* revisr_post_pull
* revisr_pre_push
* revisr_post_push
* revisr_pre_db_import
* revisr_post_db_import
* revisr_pre_discard
* revisr_post_discard

Also look into adding filters for default items such as statuses, numbers of things, etc

**Comment by fastmover** [comment]
revisr_post_db_import would be super useful.

**Comment by mgshaw** [comment]
These hooks have been added into the 2.0 release.
