### ISSUE TITLE
Message saying that Revisr could not detect a repository

### ISSUE THREAD

**Issue by JosefJezek** [ExpandedFronts/Revisr#61]
I don't see message saying that Revisr could not detect a repository. :-(

```
Operating System	Linux
Exec() Enabled	true
Git Install Path	/usr/bin/git
Git Version	git version 1.9.1
MySQL Install Path	/usr/bin/mysql
Repository Status	No repository detected.
```

```
[26-Jun-2015 10:57:42 UTC] PHP Notice:  Undefined index: gitignore in /var/www/***/htdocs/wp-content/plugins/revisr/includes/class-revisr-settings-fields.php on line 142
```

**Comment by mgshaw** [comment]
Hi,

I'm guessing you did have a repository set up? Where was it located?

**Comment by mgshaw** [comment]
Also that undefined index is a known bug, fix is ready for next release. It shouldn't affect anything though other than showing that error when DEBUG mode is turned on.

**Comment by JosefJezek** [comment]
I dont setup git repo. I would like git init from your plugin. I have wp-config.php outside wp root.

**Comment by mgshaw** [comment]
Hi,

In that case, you should be able to add the following to your wp-config.php:

"define( 'REVISR_GIT_DIR', '/var/www/***/htdocs' );"

And it would create the repo in the htdocs folder. Alternatively you could set the path to '/var/www/***/htdocs/wp-content' to just track themes, plugins, and uploads.

**Comment by mgshaw** [comment]
Closing this since I haven't heard back, but if you run into any further issues please feel free to open a support ticket over on the WordPress plugin page. 

Thanks!
