### ISSUE TITLE
Staging and production both do daily backups

### ISSUE THREAD

**Issue by cromulus** [ExpandedFronts/Revisr#70]
Which causes merge conflicts regularly. Perhaps that setting should live in the git config and not stored in the DB?

**Comment by mgshaw** [comment]
Thanks for catching it. The above should commit just about do it and also fix another bug where saving the general settings would reset the cron, even if the value hadn't been changed.

**Comment by mgshaw** [comment]
And if you're not feeling adventurous to try the develop branch (on mission-critical/production sites), you can download a hotfix version of master w/ above patch here:
https://github.com/ExpandedFronts/Revisr/archive/issue-70.zip

Hope that helps!

**Comment by cromulus** [comment]
Thanks!
ᐧ

**Comment by mgshaw** [comment]
This fix has been merged in with the 2.0 release.
