### ISSUE TITLE
Adding Repo doesn't work

### ISSUE THREAD

**Issue by quanticnet** [ExpandedFronts/Revisr#76]
If I try to add a bitbucket hosted repo it says success, but doesn't seem to work. 
I made screenshots of what I'm seeing:
http://screencast.com/t/Q6XQ7RJO
http://screencast.com/t/BrkuYwJmlibD

I would like to push changes automatically into the repo that I created for my Wordpress site.

**Comment by mgshaw** [comment]
Hi, please open a support ticket at http://revisr.io/contact/ with a paste of the "System Info" tab so I can look into this further and help you get this working. Thanks!
