### ISSUE TITLE
SSH Connection Not Working

### ISSUE THREAD

**Issue by shannonwilcox** [ExpandedFronts/revisr#81]
I can push to my git repo on Bitbucket from the command line and with HTTPS from Revisr, but get this error with SSH in Revisr:

    Permission denied (publickey).
    fatal: The remote end hung up unexpectedly

Here is the debug info from the help section:

    Operating System	Linux
    Exec() Enabled	true
    Git Install Path	/usr/bin/git
    Git Version	   git version 1.7.11.3
    MySQL Install Path	/usr/bin/mysql
    File Permissions	   true
    Repository Path	   /home1/username/public_html/concepts/hhh
    Repository Status Click here to view.

I have uploaded my keys to my server and to Bitbucket. Any advice?

**Comment by shannonwilcox** [comment]
I did some more hunting around to make sure settings are all correct. Here are some screenshots to confirm:

There is no ENCRYPTED in the first few lines of my private key, so no password is used. Public key is on Bitbucket and private key is on my server.
![ssh-key-no-password-2015-10-22](https://cloud.githubusercontent.com/assets/3209924/10670858/770a4a06-789c-11e5-8938-f744900e9760.png)

I grabbed the SSH settings from Bitbucket and pasted into settings, though I get REMOTE NOT FOUND.
![revisr-settings-2015-10-22](https://cloud.githubusercontent.com/assets/3209924/10670910/b7701724-789c-11e5-85f3-2ee0762cb883.png)

I really like the features of this plugin. Any ideas for getting it up and running with SSH?

**Comment by mgshaw** [comment]
Hi,

Is it possible that the user running Apache is different than the user that has access to your key?

That's the most common reason I see for pushes only work through command line. What user is running the server, is it "www" or "apache", or is it the same user as "username" in the "home/username/public_html/..."?

**Comment by shannonwilcox** [comment]
I'm an amateur when it comes to Apache setup, though it appears my "home/username/public_html/..." and website project directory username are the same. I ran command line "ps aux | egrep '(apache|httpd)'" and the username was the same.

**Comment by shannonwilcox** [comment]
I did some more hunting around in the SSH and got the following output:

    <username>@hurrahpinwheels.com [~/public_html/concepts/hp]# ssh-add -l
    Could not open a connection to your authentication agent.
    <username>@hurrahpinwheels.com [~/public_html/concepts/hp]# eval `ssh-agent`
    Agent pid 25145
    <username>@hurrahpinwheels.com [~/public_html/concepts/hp]# ssh-add -l
    The agent has no identities.

It seems that I need to establish a connection to my SSH identities every time I start a new shell. Does this shed some light on the issue?

**Comment by kalyanGK1** [comment]
Hi dude 
i'm also facing the same issue remote not found
have u got any solutions?
