### ISSUE TITLE
Openshift realm

### ISSUE THREAD

**Issue by gybfefe** [ExpandedFronts/revisr#92]
My idea is that a scalable wordpress site is deployed on openshift with your wonderful plugin.
If you create a site along this article:
https://blog.openshift.com/how-to-automatically-scale-wordpress-on-openshift/
then you have to correct the method of creating plugin directory because as the source write:
https://github.com/openshift/wordpress-example you have to create that in .openshift directory.
So I downloaded and extracted your plugin there, and pushed after add commit.
The only problem that it's not finding the openshift repo. What would be your guess?
Is it possible to use the openshift repo and not create a new repo? Because after creating one:
It allows me to create a new commit, but that is not reflecting on every changes, like templates, etc.
If it would work then the commit from your plugin would solve the problem of online development.
The players of this game are Repo, Deployment, and Scaling.
It is a very good use case of backing up online changes with git to local file system.
Is it possible? To sum it up, it would use your plugin only for committing and let users clone the
online changes after that, of course further replicas on github for example can benefit the other
functions you programmed like push and pull....
I would thank your suggestion...
Best,
Ben

**Comment by mattgrshaw** [comment]
If it's not finding the repo, using the REVISR_GIT_DIR and REVISR_WORK_TREE constants to point to the full path of the repo should fix the issue.
