### ISSUE TITLE
Git interferes with WordPress background updates

### ISSUE THREAD

**Issue by ChemicalSailor** [expandedfronts/revisr#94]
Once a site is under version control automatic background updates stop working. A filter is needed to enable them again `add_filter( 'automatic_updates_is_vcs_checkout', '__return_false')`

Since Revisr has functionality to put a site under version control (for new users), it would be good to have an option to keep background updates alive.

**Comment by mattgrshaw** [comment]
This isn't really specific to Revisr, and if the core WordPress team has decided to disable automatic updates for version controlled sites by default, I think it's fair that Revisr honors that behavior.

The core filter should do the job and is better than adding yet another option and potential source of confusion to the plugin settings screen IMO.
